# This workflow will do a clean install of node dependencies, build the source code and run tests

name: 'SEO'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 10,25 * *'

jobs:
  build:
    name: 'Generate SEO files'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
      - name: Install dependencies in /seo-scripts
        run: |
          cd ./seo-scripts
          npm i
      - name: Run /seo-script/index.ts
        run: |
          cd ./seo-scripts
          npm run build:seo
      - name: Compress sitemaps
        run: tar czf ./public/sitemap.tar.gz ./public/sitemap
      - name: Archive sitemaps
        uses: actions/upload-artifact@v3
        with:
          name: sitemap
          path: |
            ./public/sitemap.tar.gz
      - name: Compress page tree
        run: tar czf ./public/departements.tar.gz ./public/departements
      - name: Archive page tree
        uses: actions/upload-artifact@v3
        with:
          name: departements
          path: |
            ./public/departements.tar.gz
